import imageMeta from "@/data/image-meta.json";

export type ImageMeta = { width: number; height: number; blurDataURL: string };

const meta: Record<string, ImageMeta> = imageMeta;

/** Dimensions and blur placeholder generated by `npm run images`. */
export function getImageMeta(src: string): ImageMeta | undefined {
  return meta[src];
}

/** Props for next/image's blur placeholder, or nothing when the image has no metadata yet. */
export function blurProps(src: string) {
  const m = meta[src];
  return m ? ({ placeholder: "blur", blurDataURL: m.blurDataURL } as const) : {};
}
